POST http://localhost:63040/content/course/list?pageNo=2&pageSize=1
Content-Type: application/json

{
    "auditStatus": "",
    "courseName": "",
    "publishStatus":""
}
###

GET http://localhost:63040/content/course-category/tree-nodes

###
GET http://localhost:63040/content/course-category/tree-nodes

###
GET http://localhost:63040/content/course/117
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ6aGFuZ3NhbiIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2OTQwNjIyMjUsImF1dGhvcml0aWVzIjpbInAxIl0sImp0aSI6IjI2YzE1ZjhiLWNlNGYtNGJhYi04YzVhLTZhMWRhYmMyZjhjOSIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.QTcyVnwDwzASdNZTufX4konSUhURFb5KdYKSWTZ-9FY


### 通过网关路由到content
GET http://localhost:63010/content/course/117
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJjcmVhdGVUaW1lXCI6XCIyMDIyLTA5LTI4VDA4OjMyOjAzXCIsXCJpZFwiOlwiNDhcIixcIm5hbWVcIjpcIuezu-e7n-euoeeQhuWRmFwiLFwicGFzc3dvcmRcIjpcIlwiLFwic2V4XCI6XCIxXCIsXCJzdGF0dXNcIjpcIjFcIixcInVzZXJuYW1lXCI6XCJhZG1pblwiLFwidXR5cGVcIjpcIjEwMTAwM1wifSIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2OTQwOTA0NzgsImF1dGhvcml0aWVzIjpbInAxIl0sImp0aSI6Ijg0NzZmOWM1LTM4M2MtNDM0Mi05OWE3LTZlNDRhMGFiZjMxZCIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.aid_mO83exDPDEz8hKOqrphvsjMO5m0mtwAvVQ11c_Y
